### PR TITLE
gbk_pua: fix 15 len, add 9 normalized vert punct

### PR DESCRIPTION
**Pull request by Artoria2e5**

### CODE REVIEW

**Comment by gumblex** [comment]
Why  `，。、：；！？〖〗`?

**Comment by Artoria2e5** [comment]
hmm, I thought presentation forms should get normalized to original characters so they are easier to get for LMs...

These forms are rare, you know.

**Comment by gumblex** [comment]
This should fix PUAs only. We should have other scripts do this kind of normalization.

**Comment by Artoria2e5** [comment]
right.

**Comment by Artoria2e5** [comment]
Let me change it to the correct normalization and then I will squash the whole thing...

**Pull request merged**
